# Generated by Django 2.0.5 on 2020-06-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(max_length=8000, verbose_name='内容')),
                ('publish_time', models.DateTimeField(verbose_name='发布时间')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_put_top', models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], null=True, verbose_name='是否置顶')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.ImageField(upload_to='./imgs', verbose_name='图片路径')),
                ('img_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='图片名称')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='imgs',
            field=models.ManyToManyField(related_name='imgs', to='report.Images', verbose_name='图片'),
        ),
    ]
