# Generated by Django 2.0.5 on 2020-06-10 21:35

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, null=True)),
                ('publish_time', models.DateTimeField(default=datetime.datetime(2020, 6, 10, 21, 35, 31, 173367), verbose_name='发布时间')),
                ('wechat_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='原始链接')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('type', models.CharField(blank=True, choices=[('R', '态势报告'), ('D', '抗疫日记')], max_length=10, null=True, verbose_name='类型')),
                ('is_put_top', models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], null=True, verbose_name='是否置顶')),
            ],
        ),
    ]
