# Generated by Django 2.0.5 on 2020-06-10 21:46

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='content',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 21, 46, 5, 866722), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='content',
            name='wechat_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='微信链接'),
        ),
    ]
