# Generated by Django 2.0.5 on 2020-06-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img_path',
            field=models.ImageField(blank=True, null=True, upload_to='./imgs', verbose_name='图片路径'),
        ),
    ]
