# Generated by Django 2.0.5 on 2020-06-10 21:46

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20200610_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=DjangoUeditor.models.UEditorField(default=1, verbose_name='内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 21, 46, 52, 202799), verbose_name='发布时间'),
        ),
    ]
