# Generated by Django 2.0.5 on 2020-06-11 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20200610_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '内容管理', 'verbose_name_plural': '内容管理'},
        ),
        migrations.AlterField(
            model_name='content',
            name='is_put_top',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否置顶'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 15, 12, 42, 639096), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('R', '态势报告'), ('D', '抗疫日记')], default=1, max_length=10, verbose_name='类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='wechat_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='微信链接'),
        ),
    ]
