# Generated by Django 2.0.5 on 2020-06-24 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20200624_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 12, 24, 5, 280618), verbose_name='发布时间'),
        ),
    ]
