# Generated by Django 2.0.5 on 2020-04-21 09:21

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='text',
            field=DjangoUeditor.models.UEditorField(verbose_name='内容'),
        ),
    ]
