# Generated by Django 2.0.5 on 2020-04-21 11:38

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200421_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='text',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
