# Generated by Django 2.0.5 on 2020-04-21 21:02

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200421_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_source_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='原始机构')),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='微博昵称')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='原始链接')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('abstract', models.CharField(blank=True, max_length=300, null=True, verbose_name='摘要')),
                ('text', DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='内容')),
                ('publish_time', models.DateTimeField(max_length=150, verbose_name='发布时间')),
                ('access_time', models.DateTimeField(max_length=150, verbose_name='获取时间')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='国家地区')),
                ('type', models.CharField(blank=True, choices=[('O', '官方通告'), ('D', '抗议指南'), ('A', '风险预警')], max_length=10, null=True, verbose_name='类型')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='ArticleSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='数据源名称')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='数据源链接')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='数据源描述')),
            ],
            options={
                'verbose_name': '文章来源',
                'verbose_name_plural': '文章来源',
            },
        ),
        migrations.DeleteModel(
            name='ArticleModel',
        ),
        migrations.AddField(
            model_name='articledata',
            name='direct_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_source', to='article.ArticleSource', verbose_name='直接来源'),
        ),
        migrations.AddField(
            model_name='articledata',
            name='original_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_source', to='article.ArticleSource', verbose_name='原始来源'),
        ),
    ]
