# Generated by Django 2.0.5 on 2020-04-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200421_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledata',
            name='access_time',
            field=models.DateTimeField(blank=True, max_length=150, null=True, verbose_name='获取时间'),
        ),
        migrations.AlterField(
            model_name='articledata',
            name='publish_time',
            field=models.DateTimeField(blank=True, max_length=150, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='articledata',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='标题'),
        ),
    ]
