# Generated by Django 2.0.5 on 2020-05-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200518_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledata',
            name='type',
            field=models.CharField(blank=True, choices=[('O', '官方要闻'), ('S', '海外信息')], max_length=10, null=True, verbose_name='类型'),
        ),
    ]
