# Generated by Django 2.0.5 on 2020-06-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20200520_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledata',
            name='type',
            field=models.CharField(blank=True, choices=[('O', '官方要闻'), ('S', '海外信息'), ('R', '态势报告')], max_length=10, null=True, verbose_name='类型'),
        ),
    ]
