# Generated by Django 2.0.5 on 2020-06-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200608_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledata',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
    ]
