# Generated by Django 2.0.5 on 2020-06-09 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20200609_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledata',
            name='publish_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 9, 11, 32, 32, 477934), null=True, verbose_name='发布时间'),
        ),
    ]
