# Generated by Django 2.0.5 on 2020-06-24 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20200609_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledata',
            name='publish_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 11, 19, 40, 226447), null=True, verbose_name='发布时间'),
        ),
    ]
