# Generated by Django 2.0.5 on 2020-05-01 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plague', '0002_auto_20200501_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiondata',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_id', to='plague.RegionBasicInfo', verbose_name='地区ID'),
        ),
    ]
