# Generated by Django 2.0.5 on 2020-05-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plague', '0004_auto_20200501_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiondata',
            name='region',
        ),
        migrations.AddField(
            model_name='regiondata',
            name='region_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='地区ID'),
        ),
    ]
