# Generated by Django 2.0.5 on 2020-05-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plague', '0005_auto_20200501_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global',
            name='day_date',
            field=models.CharField(max_length=50, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='global',
            name='update_time',
            field=models.CharField(max_length=50, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='regiondata',
            name='day_date',
            field=models.CharField(max_length=50, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='regiondata',
            name='last_updated',
            field=models.CharField(max_length=50, verbose_name='更新时间'),
        ),
    ]
