# Generated by Django 2.0.5 on 2020-04-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OEC', '0004_auto_20200424_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='oecinfo',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, '驻外使馆'), (1, '驻外总领馆'), (2, '驻外团、处')], null=True, verbose_name='使馆类型'),
        ),
        migrations.AlterField(
            model_name='oecinfo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='使馆名称'),
        ),
        migrations.AlterField(
            model_name='oecinfo',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='区域'),
        ),
    ]
